[package]
name = "advent_of_code"
version = "0.9.2"
authors = ["Felix Spöttel <1682504+fspoettel@users.noreply.github.com>"]
edition = "2021"
default-run = "advent_of_code"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[features]
test_lib = []

[dependencies]
pico-args = "0.5.0"
regex = "1.10.2"
lazy_static = { version = "1.4.0", features = [] }
itertools = "0.12.0"
nom = "7.1.3"
bytes = "1.5.0"
num = "0.4.1"
counter = "0.5.7"
